services:
  sing-box:
    image: ghcr.io/vaayne/singbox-docker:latest
    container_name: sing-box
    restart: unless-stopped
    network_mode: host
    environment:
      - DOMAIN={your-domain.com}
      - EMAIL={your-email@example.com}
      - UUID={your-uuid}
      - USERNAME={your-username}
      - PASSWORD={your-password}
      - CF_TOKEN={cf-token}
      # Options
      - PORT_TROJAN=20441
      - PORT_VLESS=20442
      - PORT_VMESS=20443
      - PORT_HYSTERIA=20444
      - PORT_TUIC=20445
      - PORT_TUIC_PROXY=20446
      - PORT_MIXED=20447
      - SOCKS_SERVER=localhost
    volumes:
      - tls-data:/tls

volumes:
  tls-data:
